-- Migration 053: Create notifications tables
-- Date: 2026-03-02
-- Description: In-app notification inbox and per-user channel preferences
--              for all notification types generated by the platform.

CREATE TABLE notifications (
  id                CHAR(36)     NOT NULL DEFAULT (UUID()),
  user_id           CHAR(36)     NOT NULL,
  company_id        CHAR(36)     NOT NULL,
  notification_type ENUM('communication_published','workflow_assigned',
                         'workflow_approved','workflow_rejected','contract_signed',
                         'vesting_event','document_uploaded','system') NOT NULL,
  title             VARCHAR(200) NOT NULL,
  body              TEXT         NOT NULL,
  action_url        VARCHAR(500) NULL,
  reference_type    VARCHAR(50)  NULL,
  reference_id      CHAR(36)     NULL,
  is_read           TINYINT(1)   NOT NULL DEFAULT 0,
  read_at           TIMESTAMP    NULL,
  created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_notif_user    FOREIGN KEY (user_id)    REFERENCES users(id),
  CONSTRAINT fk_notif_company FOREIGN KEY (company_id) REFERENCES companies(id),
  INDEX idx_notif_user_read   (user_id, is_read),
  INDEX idx_notif_user_date   (user_id, created_at),
  INDEX idx_notif_company     (company_id),
  INDEX idx_notif_ref         (reference_type, reference_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE notification_preferences (
  id                CHAR(36)  NOT NULL DEFAULT (UUID()),
  user_id           CHAR(36)  NOT NULL,
  notification_type ENUM('communication_published','workflow_assigned',
                         'workflow_approved','workflow_rejected','contract_signed',
                         'vesting_event','document_uploaded','system') NOT NULL,
  channel           ENUM('in_app','email','both','none') NOT NULL DEFAULT 'both',
  updated_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_notifpref_user_type (user_id, notification_type),
  CONSTRAINT fk_notifpref_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- DOWN (rollback)
-- DROP TABLE IF EXISTS notification_preferences;
-- DROP TABLE IF EXISTS notifications;
