// F4-SVC-002: ContractVersionService
// File: src/backend/PartnershipManager.Infrastructure/Services/ContractVersionService.cs
// Author: GitHub Copilot
// Date: 23/02/2026

using PartnershipManager.Application.Features.Contracts.DTOs;
using PartnershipManager.Domain.Entities;
using PartnershipManager.Domain.Enums;
using PartnershipManager.Domain.Exceptions;
using PartnershipManager.Domain.Interfaces;
using PartnershipManager.Domain.Interfaces.Services;

namespace PartnershipManager.Infrastructure.Services;

/// <summary>
/// Operations for contract version management and DOCX/PDF uploads.
/// </summary>
public interface IContractVersionService
{
    /// <summary>
    /// Creates a new contract from an uploaded DOCX file.
    /// Returns the newly created contract DTO (status = Draft, version 1).
    /// </summary>
    Task<ContractResponse> CreateFromUploadAsync(
        Guid clientId,
        CreateContractFromUploadRequest request,
        Stream fileStream,
        string fileName,
        string? createdBy = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Uploads a new DOCX version for an existing contract.
    /// Increments the version number and creates a ContractVersion record.
    /// </summary>
    Task<ContractVersionResponse> UploadNewVersionAsync(
        Guid contractId,
        Guid clientId,
        UploadContractVersionRequest request,
        Stream fileStream,
        string fileName,
        string? createdBy = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Records the PDF generated by the builder as version 1 of the contract.
    /// Called internally by ContractBuilderController after generation.
    /// </summary>
    Task<ContractVersionResponse> RecordBuilderVersionAsync(
        Guid contractId,
        Guid clientId,
        byte[] pdfBytes,
        string? createdBy = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Returns the full version history for a contract, ordered newest first.
    /// </summary>
    Task<IEnumerable<ContractVersionResponse>> GetVersionsAsync(
        Guid contractId,
        Guid clientId,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Opens a read stream for a specific version file.
    /// Also returns the file type so the caller can set the correct Content-Type.
    /// </summary>
    Task<(Stream Stream, DocumentFileType FileType, string FileName)> GetVersionFileAsync(
        Guid contractId,
        Guid versionId,
        Guid clientId,
        CancellationToken cancellationToken = default);
}

/// <summary>
/// Implementation of IContractVersionService
/// </summary>
public class ContractVersionService : IContractVersionService
{
    private readonly IContractRepository _contractRepository;
    private readonly IContractVersionRepository _versionRepository;
    private readonly IContractStorageService _storageService;

    public ContractVersionService(
        IContractRepository contractRepository,
        IContractVersionRepository versionRepository,
        IContractStorageService storageService)
    {
        _contractRepository = contractRepository;
        _versionRepository = versionRepository;
        _storageService = storageService;
    }

    // ─────────────────────────────────────────────────────────────────────────
    public async Task<ContractResponse> CreateFromUploadAsync(
        Guid clientId,
        CreateContractFromUploadRequest request,
        Stream fileStream,
        string fileName,
        string? createdBy = null,
        CancellationToken cancellationToken = default)
    {
        ValidateDocxFile(fileName);

        // 1. Create the contract entity
        var contract = Contract.Create(
            clientId     : clientId,
            companyId    : request.CompanyId,
            title        : request.Title,
            contractType : request.ContractType,
            description  : request.Description,
            createdBy    : createdBy != null ? Guid.TryParse(createdBy, out var uid) ? uid : null : null);

        await _contractRepository.AddAsync(contract);

        // 2. Increment version (0 → 1) and persist the file
        var versionNumber = contract.IncrementVersion();
        var hash = await _storageService.ComputeHashAsync(fileStream, cancellationToken);
        var filePath = await _storageService.SaveDocxAsync(
            contract.Id, versionNumber, fileStream, fileName, cancellationToken);

        // 3. Persist the version record
        var version = ContractVersion.Create(
            contractId    : contract.Id,
            versionNumber : versionNumber,
            filePath      : filePath,
            fileType      : DocumentFileType.Docx,
            source        : ContractVersionSource.Upload,
            fileSize      : fileStream.CanSeek ? fileStream.Length : null,
            fileHash      : hash,
            createdBy     : createdBy);

        await _versionRepository.AddAsync(version);

        // 4. Persist the incremented version counter on the contract
        await _contractRepository.UpdateAsync(contract);

        return MapContractToResponse(contract);
    }

    // ─────────────────────────────────────────────────────────────────────────
    public async Task<ContractVersionResponse> UploadNewVersionAsync(
        Guid contractId,
        Guid clientId,
        UploadContractVersionRequest request,
        Stream fileStream,
        string fileName,
        string? createdBy = null,
        CancellationToken cancellationToken = default)
    {
        ValidateDocxFile(fileName);

        var contract = await _contractRepository.GetByIdAsync(contractId, clientId)
            ?? throw new NotFoundException("Contract", contractId);

        var versionNumber = contract.IncrementVersion(
            updatedBy: createdBy != null && Guid.TryParse(createdBy, out var uid) ? uid : null);

        var hash = await _storageService.ComputeHashAsync(fileStream, cancellationToken);
        var filePath = await _storageService.SaveDocxAsync(
            contract.Id, versionNumber, fileStream, fileName, cancellationToken);

        var version = ContractVersion.Create(
            contractId    : contract.Id,
            versionNumber : versionNumber,
            filePath      : filePath,
            fileType      : DocumentFileType.Docx,
            source        : ContractVersionSource.Upload,
            fileSize      : fileStream.CanSeek ? fileStream.Length : null,
            fileHash      : hash,
            notes         : request.Notes,
            createdBy     : createdBy);

        await _versionRepository.AddAsync(version);
        await _contractRepository.UpdateAsync(contract);

        return MapVersionToResponse(version);
    }

    // ─────────────────────────────────────────────────────────────────────────
    public async Task<ContractVersionResponse> RecordBuilderVersionAsync(
        Guid contractId,
        Guid clientId,
        byte[] pdfBytes,
        string? createdBy = null,
        CancellationToken cancellationToken = default)
    {
        var contract = await _contractRepository.GetByIdAsync(contractId, clientId)
            ?? throw new NotFoundException("Contract", contractId);

        var versionNumber = contract.IncrementVersion(
            updatedBy: createdBy != null && Guid.TryParse(createdBy, out var uid) ? uid : null);

        var filePath = await _storageService.SavePdfAsync(
            contract.Id, versionNumber, pdfBytes, cancellationToken);

        using var ms = new MemoryStream(pdfBytes);
        var hash = await _storageService.ComputeHashAsync(ms, cancellationToken);

        var version = ContractVersion.Create(
            contractId    : contract.Id,
            versionNumber : versionNumber,
            filePath      : filePath,
            fileType      : DocumentFileType.Pdf,
            source        : ContractVersionSource.Builder,
            fileSize      : pdfBytes.Length,
            fileHash      : hash,
            createdBy     : createdBy);

        await _versionRepository.AddAsync(version);
        await _contractRepository.UpdateAsync(contract);

        return MapVersionToResponse(version);
    }

    // ─────────────────────────────────────────────────────────────────────────
    public async Task<IEnumerable<ContractVersionResponse>> GetVersionsAsync(
        Guid contractId,
        Guid clientId,
        CancellationToken cancellationToken = default)
    {
        // Validate the contract belongs to this client
        var contract = await _contractRepository.GetByIdAsync(contractId, clientId)
            ?? throw new NotFoundException("Contract", contractId);

        var versions = await _versionRepository.GetByContractAsync(contractId);
        return versions.Select(MapVersionToResponse);
    }

    // ─────────────────────────────────────────────────────────────────────────
    public async Task<(Stream Stream, DocumentFileType FileType, string FileName)> GetVersionFileAsync(
        Guid contractId,
        Guid versionId,
        Guid clientId,
        CancellationToken cancellationToken = default)
    {
        // Validate the contract belongs to this client
        _ = await _contractRepository.GetByIdAsync(contractId, clientId)
            ?? throw new NotFoundException("Contract", contractId);

        var version = await _versionRepository.GetByIdAsync(versionId)
            ?? throw new NotFoundException("ContractVersion", versionId);

        if (version.ContractId != contractId)
            throw new NotFoundException("ContractVersion", versionId);

        var stream = await _storageService.GetFileStreamAsync(version.FilePath, cancellationToken);
        var ext = version.FileType == DocumentFileType.Docx ? "docx" : "pdf";
        var downloadName = $"contract_v{version.VersionNumber}.{ext}";

        return (stream, version.FileType, downloadName);
    }

    // ─────────────────────────────────────────────────────────────────────────
    private static void ValidateDocxFile(string fileName)
    {
        var ext = Path.GetExtension(fileName).ToLowerInvariant();
        if (ext != ".docx")
            throw new ArgumentException(
                "Only .docx files are accepted for upload. Please convert your document to Word format (.docx).",
                nameof(fileName));
    }

    private static ContractVersionResponse MapVersionToResponse(ContractVersion v) => new()
    {
        Id            = v.Id,
        ContractId    = v.ContractId,
        VersionNumber = v.VersionNumber,
        FileType      = v.FileType.ToString().ToLowerInvariant(),
        Source        = v.Source.ToString().ToLowerInvariant(),
        FileSize      = v.FileSize,
        FileHash      = v.FileHash,
        Notes         = v.Notes,
        CreatedAt     = v.CreatedAt,
        CreatedBy     = v.CreatedBy
    };

    private static ContractResponse MapContractToResponse(Contract c) => new()
    {
        Id           = c.Id,
        ClientId     = c.ClientId,
        CompanyId    = c.CompanyId,
        Title        = c.Title,
        ContractType = c.ContractType,
        Status       = c.Status,
        TemplateId   = c.TemplateId,
        Description  = c.Description,
        CreatedAt    = c.CreatedAt,
        UpdatedAt    = c.UpdatedAt
    };
}
