// F4-ENT-001: ContractVersion Entity
// File: src/backend/PartnershipManager.Domain/Entities/Contract/ContractVersion.cs
// Author: GitHub Copilot
// Date: 23/02/2026

namespace PartnershipManager.Domain.Entities;

/// <summary>
/// Represents file format of a contract document version
/// </summary>
public enum DocumentFileType
{
    /// <summary>PDF generated by the builder (QuestPDF)</summary>
    Pdf,

    /// <summary>Word document uploaded externally</summary>
    Docx
}

/// <summary>
/// Represents the origin of a contract version
/// </summary>
public enum ContractVersionSource
{
    /// <summary>Generated by the contract builder wizard</summary>
    Builder,

    /// <summary>Manually uploaded by the user</summary>
    Upload
}

/// <summary>
/// Immutable version record for a contract document.
/// Every builder-generated PDF or external DOCX upload creates a new row.
/// </summary>
public class ContractVersion
{
    /// <summary>Primary key (UUID)</summary>
    public Guid Id { get; private set; }

    /// <summary>FK → contracts.id</summary>
    public Guid ContractId { get; private set; }

    /// <summary>Sequential version number starting at 1</summary>
    public int VersionNumber { get; private set; }

    /// <summary>Path to the stored file (local or S3)</summary>
    public string FilePath { get; private set; } = string.Empty;

    /// <summary>File size in bytes</summary>
    public long? FileSize { get; private set; }

    /// <summary>SHA-256 hash for integrity verification</summary>
    public string? FileHash { get; private set; }

    /// <summary>Format of the stored file</summary>
    public DocumentFileType FileType { get; private set; }

    /// <summary>How this version was created</summary>
    public ContractVersionSource Source { get; private set; }

    /// <summary>Optional notes about this version</summary>
    public string? Notes { get; private set; }

    /// <summary>Timestamp when this version was created</summary>
    public DateTime CreatedAt { get; private set; }

    /// <summary>User who created this version</summary>
    public string? CreatedBy { get; private set; }

    // Navigation
    public Contract Contract { get; private set; } = null!;

    // EF Core parameterless constructor
    private ContractVersion() { }

    /// <summary>
    /// Reconstitutes a version record loaded from persistence (preserves the stored Id).
    /// </summary>
    public static ContractVersion Reconstitute(
        Guid id,
        Guid contractId,
        int versionNumber,
        string filePath,
        DocumentFileType fileType,
        ContractVersionSource source,
        long? fileSize,
        string? fileHash,
        string? notes,
        string? createdBy,
        DateTime createdAt)
    {
        return new ContractVersion
        {
            Id = id,
            ContractId = contractId,
            VersionNumber = versionNumber,
            FilePath = filePath,
            FileType = fileType,
            Source = source,
            FileSize = fileSize,
            FileHash = fileHash,
            Notes = notes,
            CreatedBy = createdBy,
            CreatedAt = createdAt
        };
    }

    /// <summary>
    /// Factory method — creates a new version record
    /// </summary>
    public static ContractVersion Create(
        Guid contractId,
        int versionNumber,
        string filePath,
        DocumentFileType fileType,
        ContractVersionSource source,
        long? fileSize = null,
        string? fileHash = null,
        string? notes = null,
        string? createdBy = null)
    {
        if (contractId == Guid.Empty)
            throw new ArgumentException("ContractId cannot be empty.", nameof(contractId));
        if (versionNumber < 1)
            throw new ArgumentException("VersionNumber must be >= 1.", nameof(versionNumber));
        if (string.IsNullOrWhiteSpace(filePath))
            throw new ArgumentException("FilePath is required.", nameof(filePath));

        return new ContractVersion
        {
            Id = Guid.NewGuid(),
            ContractId = contractId,
            VersionNumber = versionNumber,
            FilePath = filePath,
            FileType = fileType,
            Source = source,
            FileSize = fileSize,
            FileHash = fileHash,
            Notes = notes,
            CreatedBy = createdBy,
            CreatedAt = DateTime.UtcNow
        };
    }
}
