// F4-SVC-001: IContractStorageService Interface
// File: src/backend/PartnershipManager.Domain/Interfaces/Services/IContractStorageService.cs
// Author: GitHub Copilot
// Date: 23/02/2026

using PartnershipManager.Domain.Entities;

namespace PartnershipManager.Domain.Interfaces.Services;

/// <summary>
/// Service responsible for persisting contract document files (PDF or DOCX)
/// and computing their integrity hashes.
/// </summary>
public interface IContractStorageService
{
    /// <summary>
    /// Saves a DOCX file uploaded by the user.
    /// Returns the relative file path used for storage.
    /// </summary>
    Task<string> SaveDocxAsync(
        Guid contractId,
        int versionNumber,
        Stream stream,
        string originalFileName,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Saves a PDF file generated by the builder.
    /// Returns the relative file path used for storage.
    /// </summary>
    Task<string> SavePdfAsync(
        Guid contractId,
        int versionNumber,
        byte[] pdfBytes,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Opens a read stream to an existing stored file.
    /// </summary>
    Task<Stream> GetFileStreamAsync(string filePath, CancellationToken cancellationToken = default);

    /// <summary>
    /// Computes the SHA-256 hash of a stream without consuming it
    /// (stream position is reset after hashing).
    /// </summary>
    Task<string> ComputeHashAsync(Stream stream, CancellationToken cancellationToken = default);

    /// <summary>
    /// Returns the MIME content-type for a given document file type.
    /// </summary>
    string GetContentType(DocumentFileType fileType);
}
