# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ppro

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: containerppro.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_764233E5363A41329D3D1614CB258A09 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_9A84F7CC56914975ACC531E3ED371182 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: containerppro.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_764233E5363A41329D3D1614CB258A09 }}/ppro:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E3A5CBFE97A843FAB689302BC87B2785 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9D420031EF614167B46DFEDF744C798B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_182B484F54FD4D0AAD7FCD2110F8D45B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ppro'
          slot-name: 'Production'
          images: 'containerppro.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_764233E5363A41329D3D1614CB258A09 }}/ppro:${{ github.sha }}'
          